### PR TITLE
[bdo.GUIloader] Ui setteable

### PR DESCRIPTION
**Pull request by netzulo**
# Issues related

- [x] #13 _close if merged_

## Description

Setteable settings starting changes

### Tests

- Please @r3peat , test with your FTP before merge, _maybe something it's broken and i need 1 commit more_

### Documentation

**Settings.xml**

``` xml
<Settings>
  <!--KeyCode_LBUTTON	KeyCode_RBUTTON	KeyCode_CANCEL	KeyCode_MBUTTON	KeyCode_BACK	KeyCode_TAB	KeyCode_CLEAR	KeyCode_RETURN	KeyCode_SHIFT	KeyCode_CONTROL	KeyCode_MENU	KeyCode_PAUSE	KeyCode_CAPITAL	KeyCode_ESCAPE	KeyCode_SPACE	KeyCode_PGUP	KeyCode_PGDN	KeyCode_END	KeyCode_HOME	KeyCode_LEFT	KeyCode_UP	KeyCode_RIGHT	KeyCode_DOWN	KeyCode_SELECT	KeyCode_PRINT	KeyCode_EXECUTE	KeyCode_SNAPSHOT	KeyCode_INSERT	KeyCode_DELETE	KeyCode_HELP	KeyCode_0	KeyCode_1	KeyCode_2	KeyCode_3	KeyCode_4	KeyCode_5	KeyCode_6	KeyCode_7	KeyCode_8	KeyCode_9	KeyCode_A	KeyCode_B	KeyCode_C	KeyCode_D	KeyCode_E	KeyCode_F	KeyCode_G	KeyCode_H	KeyCode_I	KeyCode_J	KeyCode_K	KeyCode_L	KeyCode_M	KeyCode_N	KeyCode_O	KeyCode_P	KeyCode_Q	KeyCode_R	KeyCode_S	KeyCode_T	KeyCode_U	KeyCode_V	KeyCode_W	KeyCode_X	KeyCode_Y	KeyCode_Z	KeyCode_NUMPAD0	KeyCode_NUMPAD1	KeyCode_NUMPAD2	KeyCode_NUMPAD3	KeyCode_NUMPAD4	KeyCode_NUMPAD5	KeyCode_NUMPAD6	KeyCode_NUMPAD7	KeyCode_NUMPAD8	KeyCode_NUMPAD9	KeyCode_MULTIPLY	KeyCode_ADD	KeyCode_SEPARATOR	KeyCode_SUBTRACT	KeyCode_DECIMAL	KeyCode_DIVIDE	KeyCode_F1	KeyCode_F2	KeyCode_F3	KeyCode_F4	KeyCode_F5	KeyCode_F6	KeyCode_F7	KeyCode_F8	KeyCode_F9	KeyCode_F10	KeyCode_F11	KeyCode_F12	KeyCode_F13	KeyCode_F14	KeyCode_F15	KeyCode_F16	KeyCode_F17	KeyCode_F18	KeyCode_F19	KeyCode_F20	KeyCode_F21	KeyCode_F22	KeyCode_F23	KeyCode_F24	KeyCode_OEM_2	KeyCode_OEM_3	KeyCode_OEM_7-->
  <HotKeys Reload="KeyCode_SHIFT,KeyCode_MENU,KeyCode_R" AutoBuy="KeyCode_SHIFT,KeyCode_MENU,KeyCode_B" ReloadUi="KeyCode_SHIFT,KeyCode_MENU,KeyCode_U" Minimize="KeyCode_SHIFT,KeyCode_MENU,KeyCode_M" Escape="KeyCode_SHIFT,KeyCode_MENU,KeyCode_E" Dump="KeyCode_SHIFT,KeyCode_MENU,KeyCode_D" Waypoint="KeyCode_SHIFT,KeyCode_MENU,KeyCode_W" Speedhack="KeyCode_SHIFT,KeyCode_MENU,KeyCode_S" />
  <AutoFish Enabled="0" FishDataLog="0" HighLatencyMode="0" PredictMode="1" CatchGrades="Green" IdFilterWhite="0" IdFilterGreen="44165, 40218, 43801, 43802, 16382" IdFilterBlue="0" IdFilterYellow="0" FamilyNameWhiteList="" />
  <AutoRestore Enabled="0" />
  <UIHack Enabled="1" />
  <SpeedHack GhillieMode="0">
    <Horse Enabled="1" Accel="500" Speed="500" Turn="500" Brake="500" DefaultAccel="149" DefaultSpeed="159" DefaultTurn="145" DefaultBrake="145" />
    <Ship Enabled="1" Accel="500" Speed="500" Turn="500" Brake="500" DefaultAccel="100" DefaultSpeed="100" DefaultTurn="100" DefaultBrake="100" />
    <Player Enabled="1" Movement="100" Attack="500" Cast="500" AdvancedMode="0" Factor="20" />
  </SpeedHack>
  <AutoPotion Enabled="1" HP="80" MP="30" />
  <AutoItemRegister Enabled="0">
    <Items>
      <Item Enabled="0" ItemId="40218" SellValue="0" />
    </Items>
  </AutoItemRegister>
  <AutoItemBuy Enabled="0">
    <Items>
      <Item Enabled="0" ItemId="9213" EnchantLevel="0" SessionMax="500" MaxPrice="0" IsStack="1" />
    </Items>
  </AutoItemBuy>
  <Overlay Enabled="0" GoldenChests="0">
    <Waypoints />
    <Actors>
      <!--Types: ActorType_All, ActorType_Player, ActorType_Monster, ActorType_Npc, ActorType_Vehicle, ActorType_Gate, ActorType_Alterego, ActorType_Collect, ActorType_Household, ActorType_Installation, ActorType_Deadbody-->
      <Actor Enabled="0" Type="ActorType_All" IDs="0" Color="255,0,0,255" DrawCircle="1" DrawLine="0" Thickness="1" ShowName="1" ShowActorId="1" ShowDistance="1" ShowOnWorldMap="1" ShowLevel="1" ShowHp="1" MinDistance="0" MaxDistance="0" />
      <Actor Enabled="0" Type="ActorType_Monster" IDs="0" Color="255,0,0,255" DrawCircle="1" DrawLine="0" Thickness="1" ShowName="0" ShowActorId="0" ShowDistance="0" ShowOnWorldMap="0" ShowLevel="0" ShowHp="0" MinDistance="0" MaxDistance="0" />
      <Actor Enabled="0" Type="ActorType_Collect" IDs="0" Color="0,255,0,255" DrawCircle="1" DrawLine="1" Thickness="1" ShowName="0" ShowActorId="0" ShowDistance="0" ShowOnWorldMap="0" ShowLevel="0" ShowHp="0" MinDistance="0" MaxDistance="0" />
      <Actor Enabled="0" Type="ActorType_Player" IDs="0" Color="255,0,100,255" DrawCircle="1" DrawLine="0" Thickness="1" ShowName="0" ShowActorId="0" ShowDistance="0" ShowOnWorldMap="0" ShowLevel="0" ShowHp="0" MinDistance="0" MaxDistance="0" />
      <Actor Enabled="0" Type="ActorType_Collect" IDs="37082,37097,37103,37105" Color="0,200,150,255" DrawCircle="1" DrawLine="1" Thickness="3" ShowName="0" ShowActorId="0" ShowDistance="0" ShowOnWorldMap="0" ShowLevel="0" ShowHp="0" MinDistance="0" MaxDistance="0" />
    </Actors>
  </Overlay>
  <AutoProcessing Enabled="0">
    <Items>
      <!--Types: Shaking, Grinding, Chopping, Drying, Thinning, Heating-->
      <Item Enabled="0" ItemId="4601" ProcessingType="Chopping" MinCount="5" ResultItemIds="4651,4652" Comment="Ash Timber" />
      <Item Enabled="0" ItemId="4602" ProcessingType="Chopping" MinCount="5" ResultItemIds="4654,4655" Comment="Maple Timber" />
      <Item Enabled="0" ItemId="4603" ProcessingType="Chopping" MinCount="5" ResultItemIds="4657,4658" Comment="Pine Timber" />
      <Item Enabled="0" ItemId="4604" ProcessingType="Chopping" MinCount="5" ResultItemIds="4660,4661" Comment="Birch Timber" />
      <Item Enabled="0" ItemId="4605" ProcessingType="Chopping" MinCount="10" ResultItemIds="249,4685" Comment="Log" />
      <Item Enabled="0" ItemId="4606" ProcessingType="Chopping" MinCount="5" ResultItemIds="4663,4664" Comment="Fir Timber" />
      <Item Enabled="0" ItemId="4607" ProcessingType="Chopping" MinCount="5" ResultItemIds="4666,4667" Comment="Cedar Timber" />
      <Item Enabled="0" ItemId="4608" ProcessingType="Chopping" MinCount="5" ResultItemIds="4676,4677" Comment="White Cedar Timber" />
      <Item Enabled="0" ItemId="4609" ProcessingType="Chopping" MinCount="5" ResultItemIds="4680,4681" Comment="Acacia Timber" />
      <Item Enabled="0" ItemId="4610" ProcessingType="Chopping" MinCount="5" ResultItemIds="4670,4671" Comment="Palm Timber" />
      <Item Enabled="0" ItemId="4611" ProcessingType="Chopping" MinCount="5" ResultItemIds="4673,4674" Comment="Elder Tree Timber" />
      <Item Enabled="0" ItemId="4651" ProcessingType="Chopping" MinCount="10" ResultItemIds="4652" Comment="Ash Plank" />
      <Item Enabled="0" ItemId="4654" ProcessingType="Chopping" MinCount="10" ResultItemIds="4655" Comment="Maple Plank" />
      <Item Enabled="0" ItemId="4657" ProcessingType="Chopping" MinCount="10" ResultItemIds="4658" Comment="Pine Plank" />
      <Item Enabled="0" ItemId="4660" ProcessingType="Chopping" MinCount="10" ResultItemIds="4661" Comment="Birch Plank" />
      <Item Enabled="0" ItemId="249" ProcessingType="Chopping" MinCount="10" ResultItemIds="4685" Comment="Usable Scantling" />
      <Item Enabled="0" ItemId="4663" ProcessingType="Chopping" MinCount="10" ResultItemIds="4664" Comment="Fir Plank" />
      <Item Enabled="0" ItemId="4666" ProcessingType="Chopping" MinCount="10" ResultItemIds="4667" Comment="Cedar Plank" />
      <Item Enabled="0" ItemId="4676" ProcessingType="Chopping" MinCount="10" ResultItemIds="4677" Comment="White Cedar Plank" />
      <Item Enabled="0" ItemId="4680" ProcessingType="Chopping" MinCount="10" ResultItemIds="4681" Comment="Acacia Plank" />
      <Item Enabled="0" ItemId="4670" ProcessingType="Chopping" MinCount="10" ResultItemIds="4671" Comment="Palm Plank" />
      <Item Enabled="0" ItemId="4673" ProcessingType="Chopping" MinCount="10" ResultItemIds="4674" Comment="Elder Tree Plank" />
    </Items>
  </AutoProcessing>
</Settings>
```

### CODE REVIEW

**Comment by Acen** [comment]
I was under the impression that the UI was only changeable via the file. Is there a view as part of the app which a standard form?

**Comment by netzulo** [comment]
@Acen just im trying to improve configuration for **all users** :S

**Comment by Acen** [comment]
Wait, so there is a form somewhere?

**Comment by netzulo** [comment]
now yes @Acen , but depends if @r3peat accept it's xD and including this, forms still not working, just a first phase :)

**Pull request merged**
